image: node:lts

cache:
  paths:
    - node_modules

before_script:
  - yarn

pages:
  script:
    - RPC=https://regen.chorus.one:26657 STARGATE=https://regen-lcd.chorus.one:1317 yarn build:ui
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - develop
