image: node:lts

cache:
  paths:
    - node_modules

before_script:
  - yarn

pages:
  script:
    - RPC=https://xrn-us-east-1.regen.network:444 STARGATE=https://xrn-us-east-1.regen.network yarn build:ui
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - develop
