image: node:lts

cache:
  paths:
    - node_modules

before_script:
  - RPC=http://xrn-us-east-1.regen.network:26657 STARGATE=http://xrn-us-east-1.regen.network:1317 yarn

pages:
  script:
    - yarn build:ui
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - develop
